import 'dart:typed_data';

import 'package:excel/excel.dart';
import 'package:smart_meters_core/smart_meters_core.dart';

import 'report_export_log.dart';
import 'report_models.dart';
import 'report_text_sanitize.dart';

class ExcelReportService {
  Future<Uint8List> buildAllSitesExcel(AllSitesReportBundle bundle) async {
    reportExportLog('H', 'buildAllSitesExcel start');
    final excel = Excel.createExcel();
    final summary = _ensureSheet(excel, 'Summary');
    _writeSummarySheet(summary, bundle.meta, [
      ['Accessible sites', '${bundle.sites.length}'],
    ]);
    _writeSitesSheet(_ensureSheet(excel, 'Sites'), bundle);
    _writeAlertsSheet(_ensureSheet(excel, 'Alerts'), bundle.alerts);
    _removeDefaultSheetIfUnused(excel);
    final bytes = _encodeExcel(excel);
    reportExportLog('H', 'buildAllSitesExcel ok (${bytes.length} bytes)');
    return bytes;
  }

  Future<Uint8List> buildSiteExcel({
    required SiteReportBundle bundle,
    required ReportType type,
  }) async {
    reportExportLog('H', 'buildSiteExcel start ($type)');
    final excel = Excel.createExcel();
    _writeSummarySheet(
      _ensureSheet(excel, 'Summary'),
      bundle.meta,
      _summaryRows(bundle),
    );
    _writeCategoriesSheet(_ensureSheet(excel, 'Categories'), bundle);
    _writeMetersSheet(_ensureSheet(excel, 'Meters'), bundle);
    _writeReadingsSheet(_ensureSheet(excel, 'Readings'), bundle);
    _writeConsumptionTrendSheet(_ensureSheet(excel, 'Consumption Trend'), bundle);
    _writeRankingSheet(_ensureSheet(excel, 'Meter Ranking'), bundle);
    if (bundle.copResults.isNotEmpty) {
      _writeCopSheet(_ensureSheet(excel, 'COP'), bundle);
    }
    _writeAlertsSheet(_ensureSheet(excel, 'Alerts'), bundle.alerts);
    _removeDefaultSheetIfUnused(excel);
    final bytes = _encodeExcel(excel);
    reportExportLog('H', 'buildSiteExcel ok (${bytes.length} bytes)');
    return bytes;
  }

  Future<Uint8List> buildReadingsExcel(SiteReportBundle bundle) async {
    reportExportLog('H', 'buildReadingsExcel start');
    final excel = Excel.createExcel();
    final sheet = _ensureSheet(excel, 'Readings');
    _writeReadingsSheet(sheet, bundle);
    _removeDefaultSheetIfUnused(excel);
    final bytes = _encodeExcel(excel);
    reportExportLog('H', 'buildReadingsExcel ok (${bytes.length} bytes)');
    return bytes;
  }

  Uint8List _encodeExcel(Excel excel) {
    final encoded = excel.encode();
    if (encoded == null || encoded.isEmpty) {
      throw StateError('Excel generation produced empty output');
    }
    return Uint8List.fromList(encoded);
  }

  Sheet _ensureSheet(Excel excel, String name) {
    if (excel.sheets.keys.contains(name)) {
      return excel[name];
    }
    final template = excel.sheets.keys.first;
    excel.copy(template, name);
    return excel[name];
  }

  void _removeDefaultSheetIfUnused(Excel excel) {
    const defaults = {'Sheet1', 'sheet1'};
    for (final name in defaults) {
      if (name != 'Summary' && excel.sheets.keys.contains(name)) {
        excel.delete(name);
      }
    }
  }

  void _writeSummarySheet(
    Sheet sheet,
    ReportMeta meta,
    List<List<String>> rows,
  ) {
    var row = 0;
    _setRow(sheet, row++, ['Report', meta.title], bold: true);
    if (meta.siteName != null) _setRow(sheet, row++, ['Site', meta.siteName!]);
    if (meta.zoneName != null) _setRow(sheet, row++, ['Zone', meta.zoneName!]);
    if (meta.siteType != null) _setRow(sheet, row++, ['Type', meta.siteType!]);
    if (meta.location != null && meta.location!.trim().isNotEmpty) {
      _setRow(sheet, row++, ['Location', meta.location!]);
    }
    _setRow(sheet, row++, ['Period', meta.period.label]);
    _setRow(sheet, row++, ['Generated', _formatDateTime(meta.generatedAt)]);
    _setRow(sheet, row++, ['Generated by', meta.generatedByEmail]);
    row++;
    for (final entry in rows) {
      _setRow(sheet, row++, entry);
    }
  }

  List<List<String>> _summaryRows(SiteReportBundle bundle) {
    final summary = bundle.summary;
    return [
      ['Total meters', '${summary.totalMeters}'],
      ['Active meters', '${summary.activeMeters}'],
      ['Submitted today', '${summary.readingsSubmittedToday}'],
      ['Pending today', '${summary.pendingReadingsToday}'],
      ['Categories', '${summary.categoriesCount}'],
      [
        'Last reading',
        summary.lastReadingDate == null
            ? '-'
            : formatBusinessDate(summary.lastReadingDate!),
      ],
    ];
  }

  void _writeSitesSheet(Sheet sheet, AllSitesReportBundle bundle) {
    _setRow(
      sheet,
      0,
      ['Site', 'Zone', 'Type', 'Location', 'Meters', 'Today', 'Last Reading'],
      bold: true,
    );
    var row = 1;
    for (final item in bundle.sites) {
      _setRow(sheet, row++, [
        item.site.nameEn,
        item.site.displayZoneName,
        item.site.siteType.label,
        item.site.location ?? '',
        '${item.meterCount}',
        item.todayProgressLabel,
        item.lastReadingDate == null
            ? ''
            : formatBusinessDate(item.lastReadingDate!),
      ]);
    }
  }

  void _writeCategoriesSheet(Sheet sheet, SiteReportBundle bundle) {
    _setRow(
      sheet,
      0,
      ['Category', 'Meters', 'Submitted Today', 'Pending', 'Today Consumption', 'Unit'],
      bold: true,
    );
    var row = 1;
    for (final item in bundle.categories) {
      _setRow(sheet, row++, [
        item.category.displayName,
        '${item.meterCount}',
        '${item.readingsSubmittedToday}',
        '${item.pendingToday}',
        item.totalDailyConsumption?.toStringAsFixed(2) ?? '',
        item.category.baseUnitCode,
      ]);
    }
  }

  void _writeMetersSheet(Sheet sheet, SiteReportBundle bundle) {
    _setRow(
      sheet,
      0,
      ['Code', 'Name', 'Category', 'Source', 'Unit', 'Level', 'Active', 'Latest', 'Today'],
      bold: true,
    );
    var row = 1;
    for (final meter in bundle.meters.take(2000)) {
      _setRow(sheet, row++, [
        meter.meterCode,
        meter.nameEn,
        meter.categoryName,
        meter.sourceName,
        meter.unitLabel,
        meter.level.label,
        meter.isActive ? 'Yes' : 'No',
        meter.latestRawValue?.toString() ?? '',
        meter.hasSubmittedToday ? 'Submitted' : 'Pending',
      ]);
    }
  }

  void _writeReadingsSheet(Sheet sheet, SiteReportBundle bundle) {
    _setRow(
      sheet,
      0,
      [
        'Site',
        'Zone',
        'Meter Code',
        'Meter Name',
        'Category',
        'Source',
        'Unit',
        'Reading Date',
        'Value',
        'Normalized Value',
        'Consumption',
        'User',
        'Note',
        'Image Path',
      ],
      bold: true,
    );
    var row = 1;
    for (final item in bundle.readings.take(5000)) {
      _setRow(sheet, row++, [
        item.siteName,
        item.zoneName,
        item.meterCode,
        item.meterName,
        item.categoryName,
        item.sourceName,
        item.unitLabel,
        formatBusinessDate(item.reading.readingDate),
        item.reading.rawValue.toString(),
        item.reading.normalizedValue.toString(),
        item.dailyConsumption?.toString() ?? '',
        item.enteredByName?.trim().isNotEmpty == true
            ? item.enteredByName!
            : item.enteredByEmail ?? '',
        item.reading.note ?? '',
        item.reading.imageStoragePath ?? '',
      ]);
    }
  }

  void _writeConsumptionTrendSheet(Sheet sheet, SiteReportBundle bundle) {
    _setRow(sheet, 0, ['Category', 'Unit', 'Date', 'Consumption'], bold: true);
    var row = 1;
    for (final series in bundle.consumptionTrend.series) {
      for (final point in series.points.take(500)) {
        _setRow(sheet, row++, [
          series.categoryName,
          series.unitCode,
          point.label ?? formatBusinessDate(point.date),
          point.value.toStringAsFixed(2),
        ]);
      }
    }
    if (row == 1) {
      _setRow(
        sheet,
        row,
        [bundle.consumptionTrend.emptyMessage ?? 'No consumption data for this period', '', '', ''],
      );
    }
  }

  void _writeRankingSheet(Sheet sheet, SiteReportBundle bundle) {
    _setRow(sheet, 0, ['Category', 'Meter Code', 'Meter Name', 'Total Consumption'], bold: true);
    var row = 1;
    for (final entry in bundle.categoryRankings.entries) {
      final category = bundle.categories
              .where((c) => c.category.id == entry.key)
              .map((c) => c.category.displayName)
              .firstOrNull ??
          'Category';
      for (final item in entry.value.take(200)) {
        _setRow(sheet, row++, [
          category,
          item.meterCode,
          item.meterName,
          item.totalConsumption.toStringAsFixed(2),
        ]);
      }
    }
    if (row == 1) {
      _setRow(sheet, row, ['No ranking data for this period', '', '', '']);
    }
  }

  void _writeCopSheet(Sheet sheet, SiteReportBundle bundle) {
    _setRow(
      sheet,
      0,
      ['Group', 'Date', 'COP', 'BTU Consumption', 'Electricity Consumption', 'Avg', 'Min', 'Max'],
      bold: true,
    );
    var row = 1;
    for (final cop in bundle.copResults) {
      if (!cop.hasData) {
        _setRow(sheet, row++, [
          cop.copGroupName,
          '',
          cop.emptyMessage ?? 'Not enough data',
          '',
          '',
          '',
          '',
          '',
        ]);
        continue;
      }
      for (final point in cop.points.take(500)) {
        _setRow(sheet, row++, [
          cop.copGroupName,
          formatBusinessDate(point.date),
          point.cop?.toStringAsFixed(2) ?? '',
          point.btuConsumption?.toStringAsFixed(2) ?? '',
          point.electricityConsumption?.toStringAsFixed(2) ?? '',
          cop.averageCop?.toStringAsFixed(2) ?? '',
          cop.minCop?.toStringAsFixed(2) ?? '',
          cop.maxCop?.toStringAsFixed(2) ?? '',
        ]);
      }
    }
  }

  void _writeAlertsSheet(Sheet sheet, List<DashboardAlert> alerts) {
    _setRow(
      sheet,
      0,
      ['Severity', 'Type', 'Site', 'Zone', 'Meter', 'Category', 'Title', 'Message', 'Action'],
      bold: true,
    );
    if (alerts.isEmpty) {
      _setRow(sheet, 1, ['No active alerts', '', '', '', '', '', '', '', '']);
      return;
    }
    var row = 1;
    for (final alert in alerts.take(500)) {
      _setRow(sheet, row++, [
        alert.severity.label,
        alert.type.label,
        alert.siteName,
        alert.zoneName,
        alert.meterCode ?? '',
        alert.categoryName ?? '',
        alert.title,
        alert.message,
        alert.suggestedAction ?? '',
      ]);
    }
  }

  void _setRow(
    Sheet sheet,
    int rowIndex,
    List<dynamic> values, {
    bool bold = false,
  }) {
    for (var col = 0; col < values.length; col++) {
      final cell = sheet.cell(
        CellIndex.indexByColumnRow(columnIndex: col, rowIndex: rowIndex),
      );
      cell.value = TextCellValue(sanitizeExcelCell(values[col]));
      if (bold) {
        cell.cellStyle = CellStyle(bold: true);
      }
    }
  }

  String _formatDateTime(DateTime value) {
    final local = value.toLocal();
    final h = local.hour.toString().padLeft(2, '0');
    final m = local.minute.toString().padLeft(2, '0');
    return '${formatBusinessDate(local)} $h:$m';
  }
}
